"""harness.task — 向后兼容 re-export（内容已迁移至 harness.tasks）。"""

from harness.tasks import (  # noqa: F401
    BaseTask,
    Dialogue,
    DialogueOutput,
    DialogueProgressEvent,
    DialogueTurn,
    FunctionTask,
    LLMTask,
    Parallel,
    PipelineResult,
    PipelineStep,
    PollingTask,
    Result,
    Role,
    ShellTask,
    Task,
    TaskConfig,
    result_by_type,
)

__all__ = [
    "BaseTask",
    "Dialogue",
    "DialogueOutput",
    "DialogueProgressEvent",
    "DialogueTurn",
    "FunctionTask",
    "LLMTask",
    "Parallel",
    "PipelineResult",
    "PipelineStep",
    "PollingTask",
    "Result",
    "Role",
    "ShellTask",
    "Task",
    "TaskConfig",
    "result_by_type",
]
